spring.application.name=onlinestore
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/onlinestore
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.jpa.show-sql=true
server.port=8080

